
application.name: myDemoInDemo


app:
  version: @server.version@   ## @server.version@  将在mvn compile的时候被pom文件中定义的<server.version>2.0.0</server.version>替换
  name: @project.artifactId@
  build:
    time: @server.build.time@
